#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  1 16:21:48 2018

@author: atatarian
"""
print("I'm thinking of a number 1-100...")

import numpy
    
num = numpy.random.choice(101)

guess = -1

while num != guess:
    guess = int(raw_input())
    
    if guess > num:
        print('Lower')
    
    elif guess == num:
        print('Correct!')

    else:
        print('Higher')